GET http://localhost:8080/hello
###

GET http://localhost:8080/firstVerse
###

POST http://localhost:8080/upperCase
Content-Type: text/plain

to uppercase
###

POST http://localhost:8080/logMessage
Content-Type: text/plain

message
###
GET http://localhost:8080/